App\Entity\HockeyTeam:
    type: entity
    table: hockey_team
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
        createdon:
            type: datetime
            nullable: true
            options:
                default: sysdate()
            column: createdOn
    lifecycleCallbacks: {  }
